--SQL para criação das tabelas

CREATE TABLE IF NOT EXISTS instituicoes(
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    nome VARCHAR(150) NOT NULL,
    razao_social VARCHAR(150) NOT NULL
);

CREATE TABLE IF NOT EXISTS cursos(
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    nome_curso VARCHAR(150) NOT NULL,
    id_instituicao INTEGER NOT NULL,
    FOREIGN KEY (id_instituicao) REFERENCES instituicoes(id) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS turmas(
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    nome_turma VARCHAR(150) NOT NULL,
    curso_id INTEGER NOT NULL,
    instituicao_id INTEGER NOT NULL,
    FOREIGN KEY (curso_id) REFERENCES cursos(id) ON DELETE CASCADE ON UPDATE CASCADE,
    FOREIGN KEY (instituicao_id) REFERENCES instituicoes(id) ON DELETE CASCADE ON UPDATE CASCADE
);